//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postmen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postmen()
        {
            this.PostmanLocations = new HashSet<PostmanLocations>();
            this.PostmanSessions = new HashSet<PostmanSessions>();
        }
    
        public int Id { get; set; }
        public int PostmanTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> TownId { get; set; }
        public string MobileNumber { get; set; }
        public int Status { get; set; }
        public System.DateTime RegDateTime { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ImageName { get; set; }
        public string SmartNumber { get; set; }
        public string ActiveCode { get; set; }
        public string NationalCode { get; set; }
        public int PostOfficeId { get; set; }
        public string NationalCard { get; set; }
        public string BirthCard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostmanLocations> PostmanLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostmanSessions> PostmanSessions { get; set; }
    }
}
