//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRequests
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int OriginTownId { get; set; }
        public string Origin { get; set; }
        public int DetinationTownId { get; set; }
        public string Destination { get; set; }
        public string Weight { get; set; }
        public string Volume { get; set; }
        public int PostmanTypeId { get; set; }
        public int Status { get; set; }
        public System.DateTime DateTime { get; set; }
        public string ImageName { get; set; }
        public string SenderPostalCode { get; set; }
        public string RecieverPostalCode { get; set; }
        public string RecieverFirstName { get; set; }
        public string RecieverLastName { get; set; }
        public string BarCode { get; set; }
        public string Code { get; set; }
        public int ParcelServiceType { get; set; }
        public int ParcelType { get; set; }
        public bool NonStandardPackage { get; set; }
        public int InsuranceType { get; set; }
        public int SpsReceiveTimeType { get; set; }
        public long InsurSayAmount { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PriceSum { get; set; }
        public string PackageId { get; set; }
        public string DestinationLatitude { get; set; }
        public string DestinationLongitiude { get; set; }
        public string OriginLongitiude { get; set; }
        public string OriginLatitude { get; set; }
        public string SenderMobileNumber { get; set; }
        public string RecieverMobileNumber { get; set; }
        public bool IsLiquid { get; set; }
        public bool IsBreakable { get; set; }
        public int PostOfficeId { get; set; }
    }
}
